### ISSUE TITLE
Installation on Minikube/Cygwin

### ISSUE THREAD

**Issue by ruichuan** [knix-microfunctions/knix#12]
bose@N-20N3PF1BFZYW ~/knix-0.8.1/HttpFrontend
$ make
docker run --rm -it --name frontend-thrift \
        --user `id -u`:`id -g` \
        -v /home/bose/knix-0.8.1/HttpFrontend/../DataLayerService:/usr/src/datalayer \
        -v /home/bose/knix-0.8.1/HttpFrontend:/usr/src/frontend -w /usr/src/frontend \
        thrift:0.12.0 \
        bash -c 'thrift --gen java -out ./src/main/java/ /usr/src/datalayer/thrift/DataLayerMessage.thrift; thrift --gen java -out ./src/main/java/ /usr/src/datalayer/thrift/DataLayerService.thrift'
Output directory ./src/main/java/ is unusable: No such file or directory
Output directory ./src/main/java/ is unusable: No such file or directory
make: *** [Makefile:22: src/main/java/data_layer] Error 255

**Comment by iakkus** [comment]
That seems to be working in a bare metal build. Does it have something to do with folder permissions in cygwin?

**Comment by ruichuan** [comment]
yes, I also confirm that this works with ansible.

**Comment by paarijaat** [comment]
This is not a bug but a feature request. We have never targeted Cygwin and Minikube for our setup scripts/environment and nor have we tested this configuration either. For our ansible based setup the requirement is a debian based linux setup (either inside a VM or on bare metal). For the helm charts our requirements are a proper k8s cluster (not minikube) with knative running on it.

**Comment by manuelstein** [comment]
Interesting issue.
Docker should have set the working directory to /usr/src/frontend but thrift complains about the directory ./src/main/java/ missing. Also, container user should have been set with --user to the same as the user running the build.

@ruichuan, please check the ownership of your clone /home/bose/knix-0.8.1/HttpFrontend/src/main/java and the output of id -u and id -g. The ownership shall match the current user.
If it was a cygwin problem, we might be able to narrow it down. Please run cygwin and try the thrift command with an absolute container path (change Makefile to use -out /usr/src/frontend/src/main/java/ instead of -out ./src/main/java). 
Please let us know the output using absolute paths.
