### ISSUE TITLE
mfn_cli and mfn_sdk setup.py error

### ISSUE THREAD

**Issue by yannjor** [knix-microfunctions/knix#26]
[mfn_cli](https://github.com/knix-microfunctions/knix/blob/master/mfn_cli/setup.py) and [mfn_sdk](https://github.com/knix-microfunctions/knix/blob/master/mfn_sdk/setup.py) setup.py fail with IllegalStateExceprion.

This issue was encountered while running the OSS Review Toolkit's [analyzer](https://github.com/oss-review-toolkit/ort#analyzer) on Knix. The tool was run natively on a linux amd64 system.

Are there maybe some missing arguments in the setup?

Here is the exact error output:

```
PIP::mfn_cli/setup.py:
2020-05-26T11:29:29.887Z [ERROR]: PIP - Resolving dependencies for 'setup.py' failed with: IllegalStateException: setupName must not be null

PIP::mfn_sdk/setup.py:
2020-05-26T11:29:23.333Z [ERROR]: PIP - Resolving dependencies for 'setup.py' failed with: IllegalStateException: setupName must not be null
```

**Comment by iakkus** [comment]
Hi, thanks for filing this issue!

The following link suggests that the setup.py can be used with a configuration file (i.e., setup.cfg).

(https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files)

This might be the reason why you see those errors in the tool. All I could find related to this topic is [this issue](https://github.com/oss-review-toolkit/ort/issues/690), but it's not clear whether setup.cfg cases are handled.

**Comment by manuelstein** [comment]
Hi yannjor, thank you for analyzing our sources with that ORT. Your help is very much appreciated!
I went through https://github.com/oss-review-toolkit/ort/blob/master/analyzer/src/main/kotlin/managers/Pip.kt and my guess is that pydep-run.sh returns no value in project_name for setupName.
Can you confirm this? If that is correct, the problem is in pydep or ORT, not here. I'm not experiencing any trouble packaging and installing our packages with our current code.

**Comment by yannjor** [comment]
Hi Manuel, thank you for your comment! You are right that pydep-run.py will return "None" in project_name and that is the reason for the error. I will talk about this with the ORT guys.
