### ISSUE TITLE
Perform storage operations for GUI and CLI via management service (and remove the Jetty frontend)

### ISSUE THREAD

**Issue by paarijaat** [knix-microfunctions/knix#28]
### Describe the feature

Currently a jetty based frontend handles storage requests from the GUI and the CLI. The frontend queries the management service to authenticate the token received along with the request. Once the token is verified it contacts a Datalayer cache over the thrift interface to perform the necessary storage operation. 

As the actions performed by the frontend are stateless they can be safely moved into the management service as an additional action - "storageOperation".

### Benefits
* Removes an entire component from the system, hence decreases the susceptibility of the system to faults
* Additional roundtrip to the management service (to verify tokens) is saved.

### Requires changing: 
Management service, GUI, CLI.

**Comment by iakkus** [comment]
As the HttpFrontend component is getting removed, we'd also need to move the HttpFrontend/nginx_config/ somewhere else and update the relevant ansible/helm files.

**Comment by iakkus** [comment]
@paarijaat do you have a branch for this?

**Comment by iakkus** [comment]
Branch [feature/storage_ops_via_management_remove_httpfrontend](https://github.com/knix-microfunctions/knix/tree/feature/storage_ops_via_management_remove_httpfrontend).

**Comment by iakkus** [comment]
So far, we had always allowed access to the KV store in the GUI. Do you think we should also supply the functions to access the rest of the data structures (i.e., maps, sets, counters) @paarijaat @abeckn?

(I guess after the issue related to the storage triggers (#31), we can also add those as well, but those should be handled perhaps from that branch and not this one.)

By the way, do we envision a single function with different parameters (e.g., "op"="getMap", params={"name": mapname, "is_private": true}, "op"="getSet", params={"name": setname, "is_private": false})? Or do we envision a separate function for each operation? 

I think a single function would suffice; otherwise, there would be 30+ functions just for storage access, which might a bit inefficient, assuming the access to such data is not really the most frequent ones (compared to other management actions).
